apiVersion: v1
kind: ConfigMap
metadata:
  name: moving-shapes-colors
data:
  CIRCLE_COLOR: "pink"
  OVAL_COLOR: "lightgreen"
  SQUARE_COLOR: "orange"
  TRIANGLE_COLOR: "white"   # use white to get a Degraded message in ArgoCD
  RECTANGLE_COLOR: "blue" 


    # data:
    # resource.customizations.health.ConfigMap: |
    #   hs = {}
    #   hs.status = "Healthy"
    #    if obj.data.TRIANGLE_COLOR == "white" then
    #       hs.status = "Degraded"
    #       hs.message = "Use any color other than White "
    #    end
    #   return hs

    # kubectl patch configmap argocd-cm -n argocd --patch-file patch.yaml